### ISSUE TITLE
use regex with ignore param?

### ISSUE THREAD

**Issue by sckott** [ropensci/hunspell#1]
does it makes sense to allow regex matching for `ignore` param

e..g, ignore any words that start with `w`  in `c("wiskey", "whine", "water")`

i don’t know if its possible with hunspell

**Comment by jeroen** [comment]
I don't think this is possible with hunspell. The hunspell library has it's own pattern matching syntax for words which allows to define a word with all it's variations / conjugations / inflections. Regexes don't really make sense because they are rarely sufficient to define natural language.

**Comment by Dietr1ch** [comment]
While regexes are not enough to capture natural language, I think they are good enough for detecting structured text.

I'm dealing with this,

```org
:PROPERTIES:
:ID: f9c1f13f-b8cd-4076-a139-d4a8ca2885ce
:END:
#+title: My title

Document...
```

and I'm getting the UUID broken into 5 "misspelt words", `f9c1f13f`, `b8cd`, `4076`, `a139` and `d4a8ca2885ce`, all which are obviously not words that should be added to my local dictionary as a workaround.

It'd be nice to be able to tell hunspell that the line is not going to make sense, and using `^:ID:` would be enough to pass down that exception.

**Comment by jeroen** [comment]
I think it is easier for you to filter those lines out before passing them to `hunspell()`.

```r
txt <- readLines("yourdoc.txt")
txt <- grep('^:ID:', txt, value = TRUE, invert = TRUE)
hunspell::hunspell(txt)
```
