### ISSUE TITLE
failed installing

### ISSUE THREAD

**Issue by thierrygosselin** [ropensci/hunspell#10]
Warning in install.packages :
  URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/hunspell_1.4.2.tgz': status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot download all files
Warning in install.packages :
  download of package ‘hunspell’ failed

Using compilation from source:
Do you want to install from sources the package which needs compilation?
y/n: y
installing the source package ‘hunspell’

trying URL 'https://cran.rstudio.com/src/contrib/hunspell_1.4.3.tar.gz'
Content type 'application/x-gzip' length 2756073 bytes (2.6 MB)
==================================================
downloaded 2.6 MB

* installing *source* package ‘hunspell’ ...
** package ‘hunspell’ successfully unpacked and MD5 sums checked
** libs
clang++ -std=c++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I. -Ihunspell -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include"  -fopenmp -std=c++11 -fPIC  -Wall -mtune=core2 -g -O2 -c RcppExports.cpp -o RcppExports.o
clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘hunspell’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/hunspell’
Warning in install.packages :
  installation of package ‘hunspell’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/l_/vmf27bgn4yv1fbdc_kghmzy00000gn/T/Rtmp88pnjW/downloaded_packages’

**Comment by jeroenooms** [comment]
There is something wrong with your R installation. You're passing an `-fopenmp` flag to the compiler which shouldn't be there. Probably in your `~/R/environment` or so.

**Comment by thierrygosselin** [comment]
the -fopenmp is required if I want to run Random Forest on multiple CPU...

**Comment by jeroenooms** [comment]
well according to your own output, you're setting it somewhere where it is not supported...

**Comment by thierrygosselin** [comment]
Turned off `-fopenmp` flag in `~/.R/Makevars` file and it worked with `install.packages("hunspell")`.

First time I get problem with `-fopenmp` option during install...

**Comment by jeroenooms** [comment]
I guess you usually don't install packages from source? There is really nothing special about the hunspell package.
