### ISSUE TITLE
Compiling the hunspell package is failing with R-devel

### ISSUE THREAD

**Issue by jimhester** [ropensci/hunspell#12]
At least on travis (https://travis-ci.org/hadley/devtools/jobs/153316405#L1973-L2025). This is breaking only R-devel builds of devtools, release and old-release both are working fine.

It looks like something weird is going on with the includes, not sure what would be causing it as the CRAN check for R devel looks fine (https://cran.r-project.org/web/checks/check_results_hunspell.html).

**Comment by jeroenooms** [comment]
It's missing a dash in front of `I/home/travis/R-bin/lib/R/include`.

**Comment by jeroenooms** [comment]
No it's completely missing the `c++` part. That must be a bug in r-devel...

**Comment by jeroenooms** [comment]
Does this not happen for other packages with `CXX_STD=CXX11` ?

**Comment by jeroenooms** [comment]
The same problem happens e.g. https://travis-ci.org/ropensci/tokenizers/jobs/153245449. This must be a bug in r-devel when setting `CXX_STD=CXX11`.

**Comment by jimhester** [comment]
Looks like the problem is when we are building the R versions on travis. The configure script for R-3.3.1 detects the compiler supports `-std=c++0x` and sets the C++11 compiler appropriately (https://travis-ci.org/jimhester/r-source/builds/139761784#L3407), however the current R-devel must be using a stricter test of compilance, because the same compiler toolchain fails to find any C++11 compiler (https://travis-ci.org/wch/r-source#L3460).

**Comment by jeroen** [comment]
@jimhester According to our [discussion on the bug tracker](https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17189) the stricter feature test should now be disabled for r-devel.

**Comment by jeroen** [comment]
This was fixed in base R I think.
