### ISSUE TITLE
problems with encoding in windows

### ISSUE THREAD

**Issue by dfalbel** [ropensci/hunspell#16]
This is a minimal example, although you need to install `ptstem` with:

`devtools::install_github("dfalbel/ptstem")`

```
hunspell::hunspell_stem(
    stringi::stri_enc_toutf8("balão"),
    dict = system.file("dict/Portuguese_Brazilian.dic", package = "ptstem")
  )
```

This code returns:

```
[[1]]
[1] "balÃ£o"
```

But the result should be `balão` again.
This error only happens in windows. You can also check the [appveyor log](https://ci.appveyor.com/project/dfalbel/ptstem)

**Comment by jeroenooms** [comment]
Thanks! I think this should fix it https://github.com/ropensci/hunspell/commit/9b0fb8b3d27915e9a22cadb7a688895e9f4625dc

**Comment by jeroenooms** [comment]
@dfalbel can you please test if this works now, or if you find additional related problems with the other functions?

**Comment by dfalbel** [comment]
It works now! Thanks! :)
I'll report if I find any other problem

**Comment by jeroenooms** [comment]
OK great. Thanks again for reporting this.

**Comment by jeroenooms** [comment]
FYI this is on CRAN now.
