### ISSUE TITLE
licensing a package that depends on ropensci/hunspell

### ISSUE THREAD

**Issue by dfalbel** [ropensci/hunspell#17]
If I have a package that depends on ropensci/hunspell how should I license it? Can I use a standard license like MIT?

**Comment by jeroenooms** [comment]
You can use anything you like. You are not shipping any copyrighted libhunspell source code, only your own. The user has to download the libhunspell package along with your package. Therefore you do not have to worry about license from another package, they do not affect yours (unless you copy over code from the other package into yours).

**Comment by dfalbel** [comment]
alright! thanks!
