### ISSUE TITLE
Hyphenation support?

### ISSUE THREAD

**Issue by gaborcsardi** [ropensci/hunspell#20]
AFAIR hunspell has some hyphenation support, right?

**Comment by jeroenooms** [comment]
It requires separate dictionaries, e.g.: https://packages.debian.org/sid/hyphen-hu

**Comment by gaborcsardi** [comment]
Got it. It might make sense to put it in another package. Close this issue if you like.

**Comment by jeroenooms** [comment]
I don't mind adding it, but I'm not sure it's still maintained.

**Comment by gaborcsardi** [comment]
It is in Debian, so I would not be too worried....

**Comment by brodieG** [comment]
Note [hrbrmstr lib)[https://github.com/hrbrmstr/hyphenatr]

**Comment by gaborcsardi** [comment]
@brodieG 👍
