### ISSUE TITLE
Emoji in text causes segfault

### ISSUE THREAD

**Issue by druzinis** [ropensci/hunspell#25]
Calling hunspell_suggest on a string containing a smiling face emoji results in R crashing due to segfault. Tested on versions 2.2 and 2.3. 

```
library(hunspell)
hunspell_suggest("word\U0001f60a")
```
<img width="570" alt="screenshot 2017-05-08 08 56 25" src="https://cloud.githubusercontent.com/assets/883417/25793601/98ddc12e-33cd-11e7-8c8a-b312e1b71dfb.png">

[session info v.2.2.txt](https://github.com/ropensci/hunspell/files/982594/session.info.v.2.2.txt)
[session info v.2.3.txt](https://github.com/ropensci/hunspell/files/982595/session.info.v.2.3.txt)

**Comment by jeroen** [comment]
This only seems to happen for the `en_US` dictionary. Doesn't happen for:

```r
hunspell_suggest("word\U0001f60a", dict = 'en_GB')
```

Very strange.

**Comment by jeroen** [comment]
I have updated the `en_US` dictionary and this seems to have solved the problem.
