### ISSUE TITLE
Feature request: Add ignore parameter to hunspell_stem

### ISSUE THREAD

**Issue by ssword** [ropensci/hunspell#26]
Just found this package yesterday, and I am really excited about how hunspell_stem can return natural words without stem completion. 
But I find out that this function will stem "injury", "injuries" to "jury", and "bed" to "b", which are clearly not perfect. 
So could you please add an ignore parameter to hunspell_stem, just like hunspell function, or is there a way I can change part of the mapping rules somewhere? 
Please forgive me if my question is naive since I am just started using this package. 
Thanks.

**Comment by jeroen** [comment]
You can manually add words to the dictionary:

```r
library(hunspell)
en <- dictionary(add_words = 'injury')
hunspell_stem('injury', dict = en)

```

**Comment by ssword** [comment]
Thank you Sir for the quick response.
