### ISSUE TITLE
hunspell_... returns "NA" as a string, not as a missing value

### ISSUE THREAD

**Issue by nthun** [ropensci/hunspell#27]
Hi, I think this is a bug. When you pass NA values - with a class of string - to any of the hunspell functions, it converts "NA" to a string, and returns it, instead of returning a missing value.

```
y <- NA_character_

> hunspell_parse(y)
[[1]]
[1] "NA"

> hunspell_analyze(y)
[[1]]
[1] " st:Na"

> hunspell_stem(y)
[[1]]
[1] "Na"
```

**Comment by jeroen** [comment]
Thanks! Fixed.
