### ISSUE TITLE
Including more commands in latexparser.cc

### ISSUE THREAD

**Issue by HughParsonage** [ropensci/hunspell#32]
If I understand correctly,  the following lines in `latexparser` fence off commands from the spell check.

https://github.com/ropensci/hunspell/blob/4678821d16aebb71430c17c623b664134e09b483/src/parsers/latexparser.cc#L53

Is it possible or advisable to expand this list? I was considering a pull request to do this, but I'm not sure what commands you've decided should be included in this list. For example, the command `\textcite` from `biblatex` will almost always raise false positives, but it's not part of core LaTeX, so someone could write 

```tex
\newcommand*{\textcite}[1]{\emph{#1}}
```

and then complain that the spell check missed a misspelling within it. Of course, TeX is extremely versatile in what commands can be overridden, so hunspell has to accept a level of traditional markup in order to be usable. 

By way of background, I am the maintainer of [`TeXCheckR`](https://cran.r-project.org/web/packages/TeXCheckR/index.html) which (gratefully!) imports `hunspell`.

**Comment by jeroen** [comment]
This file is from the upstream [hunspell library](https://github.com/hunspell/hunspell). You need to send PR's to them.
