### ISSUE TITLE
Stemming of "detail" and "retail" reduces to "tail"

### ISSUE THREAD

**Issue by ValeriVoev** [ropensci/hunspell#33]
I am using hunspell version 2.9 and I get the following output from hunspell_stem:

`hunspell::hunspell_stem("details")
`
returns
`
[[1]]
[1] "tail"
`
I get the same output with "retail". In my opinion detail and retail should not get reduced (stemmed) to "tail".

**Comment by jeroen** [comment]
Thank you for the report. It is better to report behavioural problems in the [upstream libhunspell](https://github.com/hunspell/hunspell) repository. The current repository only implements the R bindings, not the stemming algorithm.

**Comment by ValeriVoev** [comment]
Thanks @jeroen. Will check if that is already mentioned there or raise a new issue otherwise

**Comment by jeroen** [comment]
Closing because nothing I can do about this.
