### ISSUE TITLE
Build against system hunspell

### ISSUE THREAD

**Issue by QuLogic** [ropensci/hunspell#34]
I can delete `src/hunspell` but it looks like stuff in `src/parsers` is used and is not public API. Might this be possible in the future?

**Comment by jeroen** [comment]
No, we did use the system hunspell in previous versions of this package however it resulted in a lot of trouble. The hunspell api changed a few times and not all headers are exposed, so it's too difficult to write package that will work on various systems. Hence now we just bundle the library, unfortunately.

**Comment by jeroen** [comment]
Closing with "wontfix" because we really need to bundle because we need a consistent version of libhunspell on all different operating systems. The libhunspell library simply changes too often to use the system provided hunspell.

**Comment by Alessandro-Barbieri** [comment]
hunspell latest release is from 2018 https://github.com/hunspell/hunspell/releases/tag/v1.7.0
the issue with version changes doesn't stand anymore
