### ISSUE TITLE
Add words?

### ISSUE THREAD

**Issue by maelle** [ropensci/hunspell#4]
I'm wondering how one could easily add words to the dictionary. For instance in the texts I'll use hunspell with, I can find the Indian English word "tiffin" which does exist but hun_check returns FALSE.

Or maybe this issue is related to https://github.com/jeroenooms/hunspell/issues/3 and I should try and find an Indian English dictionary.

**Comment by jeroenooms** [comment]
You could use the `ignore` argument for this:

```r
hunspell_find("Tiffin is an Indian English word for a light midday meal", ignore = "tiffin")
```

I'll look into using custom dictionaries for the next release.

**Comment by masalmon** [comment]
Ok thank you very much, and then

```r 
 hunspell_find("Tiffin is an Indian English word for a light midday meal. I like eating dal", ignore = c("tiffin", "dal"))
```
for many words.

**Comment by masalmon** [comment]
Oops maybe it should stay open, sorry.

**Comment by jeroenooms** [comment]
FYI the `hunspell_find` function has been renamed to `hunspell` in the new release ;)

**Comment by jeroen** [comment]
Forgot to respond to this issue. The `dictionary()` function now has an `add_words parameter.
