### ISSUE TITLE
French Canadian?

### ISSUE THREAD

**Issue by Amarakon55** [ropensci/hunspell#51]
So far the only language present is English. Could you add French (Canadian) and maybe French (France)?

**Comment by jeroen** [comment]
Did you read: https://cran.r-project.org/web/packages/hunspell/vignettes/intro.html#Hunspell_Dictionaries

**Comment by Amarakon55** [comment]
Hello thanks I didn't read that until now. All I had to do was install the hunspell french language with my package manager.
