### ISSUE TITLE
When to expect v3.0.2 on CRAN?

### ISSUE THREAD

**Issue by GegznaV** [ropensci/hunspell#53]
The current GitHub version of `hunspell` has some bug fixes/updates that allow correct identification of additionally downloaded dictionaries in RStudio (besides the 4 main ones). **When can one expect `hunspell` v3.0.2 (or newer) to be uploaded to CRAN?** What is the plan?

**Comment by jeroen** [comment]
I have uploaded it to cran for you.

**Comment by GegznaV** [comment]
Thank you, @jeroen
