### ISSUE TITLE
Encoding issue when using system hunspell dictionary

### ISSUE THREAD

**Issue by tillea** [ropensci/hunspell#55]
Hi,
the Debian packaged version of the hunspell R package received a [bug report](https://bugs.debian.org/1028130) to use the dictionaries provided by Debian.  I followed that hint but this leads two to encoding issues in the test suite:

    ── Failure ('test-encodings.R:16:3'): Dictionaries are found ───────────────────
    hunspell_info("en_US")$wordchars not equal to "’".
    1/1 mismatches
    x[1]: "0123456789’"
    y[1]: "’"
    ── Failure ('test-encodings.R:17:3'): Dictionaries are found ───────────────────
    hunspell_info("en_GB")$wordchars not equal to "’".
    1/1 mismatches
    x[1]: "0123456789’"
    y[1]: "’"
    [ FAIL 2 | WARN 0 | SKIP 0 | PASS 126 ]

You can also find a [full build log reproducing these failures](https://salsa.debian.org/r-pkg-team/r-cran-hunspell/-/jobs/4924880#L470).

I wonder if you see any solution for this issue since I agree with the bug submitter that it is better to uses the dictionaries installed on the system.
Kind regards, Andreas.

**Comment by jeroen** [comment]
This is not really an encoding issue, but simply the result of using a different dictionary with different properties. 

This test is intended to verify that the dictionaries get parsed correctly. Given that you are patching the package to use other dictionaries than the ones we ship, you should probably just skip or adapt these tests (as you already did iiuc). 

I don't see any meaningful way to run tests of the parser, if you replace our testing target with something else...
