### ISSUE TITLE
put NEWS bits in releases

### ISSUE THREAD

**Issue by sckott** [ropensci/hunspell#8]
hey @jeroenooms   - We want all rOpenSci pkgs to consistently keep track of changes, following https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-news  

Thanks for using a `NEWS` file and git tagging. Could you please use the [releases tab](https://github.com/ropensci/hunspell/releases) on this repo to include the associated NEWS items for each tag/version ? thanks 😄 

Same request goes for your other repos 😄

**Comment by jeroenooms** [comment]
There already is a news file? You want me to copy the contents to the releases tab?

**Comment by sckott** [comment]
Yes, for consistency across all ropensci pkgs, is that too much trouble?
